- name: install nginx and certbot
  apt: name={{item}} state=present default_release=jessie-backports
  with_items:
    - nginx
    - certbot
- name: configure certbot to renew regularly
  cron: name="certbot" hour="15" job="certbot renew --quiet"
- name: copy nginx ssl_params
  copy: dest=/etc/nginx/ssl_params src=templates/etc/nginx/ssl_params
  notify:
    - reload nginx
- name: remove default site
  file: name=/etc/nginx/sites-enabled/default state=absent
